# Generated by Django 4.1.7 on 2023-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomiorestapi', '0002_rename_name_destination_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='id',
        ),
        migrations.AlterField(
            model_name='destination',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
